package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class documento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DOCUMENTO_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "DOCUMENTO_ID_SEQ", name = "DOCUMENTO_ID_GENERATOR")
    private java.lang.Long id;
    
    private org.jbpm.document.Document documento_adjunto;

    public documento() {
    }
    
    public documento(java.lang.Long id,org.jbpm.document.Document documento_adjunto) {
        this.id = id;
        this.documento_adjunto = documento_adjunto;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

    public org.jbpm.document.Document getDocumento_adjunto() {
        return this.documento_adjunto;
    }
    
    public void setDocumento_adjunto(org.jbpm.document.Document documento_adjunto) {
        this.documento_adjunto = documento_adjunto;
    }
}