package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class informe_avance implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "INFORME_AVANCE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "INFORME_AVANCE_ID_GENERATOR", sequenceName = "INFORME_AVANCE_ID_SEQ")
   private java.lang.Long id;
   private org.jbpm.document.Document informeavance;

   private java.lang.String periodo;

   private java.lang.String observaciones;

   public informe_avance()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public org.jbpm.document.Document getInformeavance()
   {
      return this.informeavance;
   }

   public void setInformeavance(org.jbpm.document.Document informeavance)
   {
      this.informeavance = informeavance;
   }

   public java.lang.String getPeriodo()
   {
      return this.periodo;
   }

   public void setPeriodo(java.lang.String periodo)
   {
      this.periodo = periodo;
   }

   public java.lang.String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(java.lang.String observaciones)
   {
      this.observaciones = observaciones;
   }

   public informe_avance(java.lang.Long id, org.jbpm.document.Document informeavance,
         java.lang.String periodo, java.lang.String observaciones)
   {
      this.id = id;
      this.informeavance = informeavance;
      this.periodo = periodo;
      this.observaciones = observaciones;
   }

}