package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.text.SimpleDateFormat;
import javax.persistence.Transient;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@javax.persistence.Entity
public class prorroga implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PRORROGA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PRORROGA_ID_SEQ", name = "PRORROGA_ID_GENERATOR")
   private java.lang.Long id;

   @javax.persistence.Transient
   SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

   @javax.persistence.Temporal(javax.persistence.TemporalType.DATE)
   private java.util.Date fecha_final;

   private java.lang.String justificacion;

   private java.lang.Integer duracion;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label(value = "lista_miembros")
   private java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros;

   public prorroga()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getFecha_final()
   {
      return this.fecha_final;
   }

   public void setFecha_final(java.util.Date fecha_final)
   {
      this.fecha_final = corregirFecha(fecha_final);
   }

   public java.lang.String getJustificacion()
   {
      return this.justificacion;
   }

   public void setJustificacion(java.lang.String justificacion)
   {
      this.justificacion = justificacion;
   }

   public java.lang.Integer getDuracion()
   {
      return this.duracion;
   }

   public void setDuracion(java.lang.Integer duracion)
   {
      this.duracion = duracion;
   }

   public prorroga(java.lang.Long id, java.util.Date fecha_final,
         java.lang.String justificacion, java.lang.Integer duracion)
   {
      this.id = id;
      this.fecha_final = corregirFecha(fecha_final);
      this.justificacion = justificacion;
      this.duracion = duracion;
   }

   public Date corregirFecha(Date fecha)
   {
      if (fecha != null)
      {
         int anio = Integer.parseInt(formatoFecha.format(fecha).substring(6));
         if (anio < 999)
         {
            anio += 2000;
            try
            {
               fecha = formatoFecha.parse(formatoFecha.format(fecha).substring(0, 6) + anio);
            }
            catch (ParseException ex)
            {
               System.out.println("error parse: fecha");
            }
         }
      }
      return fecha;
   }

   public java.util.List<ucuenca.tramitesdiuc.miembro> getLista_miembros()
   {
      return this.lista_miembros;
   }

   public void setLista_miembros(
         java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros)
   {
      this.lista_miembros = lista_miembros;
   }

   public prorroga(java.lang.Long id, java.text.SimpleDateFormat formatoFecha,
         java.util.Date fecha_final, java.lang.String justificacion,
         java.lang.Integer duracion,
         java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros)
   {
      this.id = id;
      this.formatoFecha = formatoFecha;
      this.fecha_final = corregirFecha(fecha_final);
      this.justificacion = justificacion;
      this.duracion = duracion;
      this.lista_miembros = lista_miembros;
   }

}