package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */
import java.text.SimpleDateFormat;
import javax.persistence.Transient;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@javax.persistence.Entity
public class tramite implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRAMITE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.Column(unique = true)
   @javax.persistence.SequenceGenerator(sequenceName = "TRAMITE_ID_SEQ", name = "TRAMITE_ID_GENERATOR")
   private java.lang.Long id;

   @javax.persistence.Transient
   SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

   private java.lang.String solicitante;

   private java.lang.String convocatoria;

   private java.lang.Integer nro_tramite;
   @javax.persistence.Temporal(javax.persistence.TemporalType.DATE)
   private java.util.Date fecha_solicitud;

   private java.lang.String titulo_proyecto;

   private java.lang.String telefono_contacto;

   private java.lang.String codigo_proyecto;

   private java.lang.String observaciones_validacion;

   private java.lang.String observaciones_aprobacion;
   @javax.persistence.Temporal(javax.persistence.TemporalType.DATE)
   private java.util.Date fecha_validacion;

   private java.lang.String respuesta;
   @javax.persistence.Temporal(javax.persistence.TemporalType.DATE)
   private java.util.Date fecha_aprobacion;
   @javax.persistence.Temporal(javax.persistence.TemporalType.DATE)
   private java.util.Date fecha_actualizacion;

   private java.lang.String observaciones_actualizacion;

   private java.lang.String estado_tramite;

   private java.lang.String tipo_tramite;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   private java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros;

   @org.kie.api.definition.type.Label("id_historial")
   private java.lang.Long id_historial;

   @org.kie.api.definition.type.Label("id_informe_avance")
   private java.lang.Long id_informe_avance;

   @org.kie.api.definition.type.Label("id_informe_final")
   private java.lang.Long id_informe_final;

   @org.kie.api.definition.type.Label("id_prorroga")
   private java.lang.Long id_prorroga;

   @org.kie.api.definition.type.Label("id_presupuesto")
   private java.lang.Long id_presupuesto;

   @org.kie.api.definition.type.Label("id_miembro")
   private java.lang.Long id_miembro;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label("documentos_adjuntos")
   private java.util.List<ucuenca.tramitesdiuc.documento> documentos_adjuntos;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "aaa")
   private java.util.List<java.lang.String> aaa;
   
   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "aa")
   private java.util.List<org.jbpm.document.Document> aa;

   public tramite()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getSolicitante()
   {
      return this.solicitante;
   }

   public void setSolicitante(java.lang.String solicitante)
   {
      this.solicitante = solicitante;
   }

   public java.lang.String getConvocatoria()
   {
      return this.convocatoria;
   }

   public void setConvocatoria(java.lang.String convocatoria)
   {
      this.convocatoria = convocatoria;
   }

   public java.lang.Integer getNro_tramite()
   {
      return this.nro_tramite;
   }

   public void setNro_tramite(java.lang.Integer nro_tramite)
   {
      this.nro_tramite = nro_tramite;
   }

   public java.util.Date getFecha_solicitud()
   {
      return this.fecha_solicitud;
   }

   public void setFecha_solicitud(java.util.Date fecha_solicitud)
   {
      this.fecha_solicitud = corregirFecha(fecha_solicitud);
   }

   public java.lang.String getTitulo_proyecto()
   {
      return this.titulo_proyecto;
   }

   public void setTitulo_proyecto(java.lang.String titulo_proyecto)
   {
      this.titulo_proyecto = titulo_proyecto;
   }

   public java.lang.String getTelefono_contacto()
   {
      return this.telefono_contacto;
   }

   public void setTelefono_contacto(java.lang.String telefono_contacto)
   {
      this.telefono_contacto = telefono_contacto;
   }

   public java.lang.String getCodigo_proyecto()
   {
      return this.codigo_proyecto;
   }

   public void setCodigo_proyecto(java.lang.String codigo_proyecto)
   {
      this.codigo_proyecto = codigo_proyecto;
   }

   public java.lang.String getObservaciones_validacion()
   {
      return this.observaciones_validacion;
   }

   public void setObservaciones_validacion(
         java.lang.String observaciones_validacion)
   {
      this.observaciones_validacion = observaciones_validacion;
   }

   public java.lang.String getObservaciones_aprobacion()
   {
      return this.observaciones_aprobacion;
   }

   public void setObservaciones_aprobacion(
         java.lang.String observaciones_aprobacion)
   {
      this.observaciones_aprobacion = observaciones_aprobacion;
   }

   public java.util.Date getFecha_validacion()
   {
      return this.fecha_validacion;
   }

   public void setFecha_validacion(java.util.Date fecha_validacion)
   {
      this.fecha_validacion = corregirFecha(fecha_validacion);
   }

   public java.lang.String getRespuesta()
   {
      return this.respuesta;
   }

   public void setRespuesta(java.lang.String respuesta)
   {
      this.respuesta = respuesta;
   }

   public java.util.Date getFecha_aprobacion()
   {
      return this.fecha_aprobacion;
   }

   public void setFecha_aprobacion(java.util.Date fecha_aprobacion)
   {
      this.fecha_aprobacion = corregirFecha(fecha_aprobacion);
   }

   public java.util.Date getFecha_actualizacion()
   {
      return this.fecha_actualizacion;
   }

   public void setFecha_actualizacion(java.util.Date fecha_actualizacion)
   {
      this.fecha_actualizacion = corregirFecha(fecha_actualizacion);
   }

   public java.lang.String getObservaciones_actualizacion()
   {
      return this.observaciones_actualizacion;
   }

   public void setObservaciones_actualizacion(
         java.lang.String observaciones_actualizacion)
   {
      this.observaciones_actualizacion = observaciones_actualizacion;
   }

   public java.lang.String getEstado_tramite()
   {
      return this.estado_tramite;
   }

   public void setEstado_tramite(java.lang.String estado_tramite)
   {
      this.estado_tramite = estado_tramite;
   }

   public java.lang.String getTipo_tramite()
   {
      return this.tipo_tramite;
   }

   public void setTipo_tramite(java.lang.String tipo_tramite)
   {
      this.tipo_tramite = tipo_tramite;
   }

   public Date corregirFecha(Date fecha)
   {
      if (fecha != null)
      {
         int anio = Integer.parseInt(formatoFecha.format(fecha).substring(6));
         if (anio < 999)
         {
            anio += 2000;
            try
            {
               fecha = formatoFecha.parse(formatoFecha.format(fecha).substring(0, 6) + anio);
            }
            catch (ParseException ex)
            {
               System.out.println("error parse: fecha");
            }
         }
      }
      return fecha;
   }

   public java.util.List<ucuenca.tramitesdiuc.miembro> getLista_miembros()
   {
      return this.lista_miembros;
   }

   public void setLista_miembros(java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros)
   {
      this.lista_miembros = lista_miembros;
   }

   public java.lang.Long getId_historial()
   {
      return this.id_historial;
   }

   public void setId_historial(java.lang.Long id_historial)
   {
      this.id_historial = id_historial;
   }

   public java.lang.Long getId_informe_avance()
   {
      return this.id_informe_avance;
   }

   public void setId_informe_avance(java.lang.Long id_informe_avance)
   {
      this.id_informe_avance = id_informe_avance;
   }

   public java.lang.Long getId_informe_final()
   {
      return this.id_informe_final;
   }

   public void setId_informe_final(java.lang.Long id_informe_final)
   {
      this.id_informe_final = id_informe_final;
   }

   public java.lang.Long getId_prorroga()
   {
      return this.id_prorroga;
   }

   public void setId_prorroga(java.lang.Long id_prorroga)
   {
      this.id_prorroga = id_prorroga;
   }

   public java.lang.Long getId_presupuesto()
   {
      return this.id_presupuesto;
   }

   public void setId_presupuesto(java.lang.Long id_presupuesto)
   {
      this.id_presupuesto = id_presupuesto;
   }

   public java.lang.Long getId_miembro()
   {
      return this.id_miembro;
   }

   public void setId_miembro(java.lang.Long id_miembro)
   {
      this.id_miembro = id_miembro;
   }

   public tramite(java.lang.Long id, java.text.SimpleDateFormat formatoFecha,
         java.lang.String solicitante, java.lang.String convocatoria,
         java.lang.Integer nro_tramite, java.util.Date fecha_solicitud,
         java.lang.String titulo_proyecto, java.lang.String telefono_contacto,
         java.lang.String codigo_proyecto,
         java.lang.String observaciones_validacion,
         java.lang.String observaciones_aprobacion,
         java.util.Date fecha_validacion, java.lang.String respuesta,
         java.util.Date fecha_aprobacion, java.util.Date fecha_actualizacion,
         java.lang.String observaciones_actualizacion,
         java.lang.String estado_tramite, java.lang.String tipo_tramite,
         java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros,
         java.lang.Long id_historial, java.lang.Long id_informe_avance,
         java.lang.Long id_informe_final, java.lang.Long id_prorroga,
         java.lang.Long id_presupuesto, java.lang.Long id_miembro)
   {
      this.id = id;
      this.formatoFecha = formatoFecha;
      this.solicitante = solicitante;
      this.convocatoria = convocatoria;
      this.nro_tramite = nro_tramite;
      this.fecha_solicitud = corregirFecha(fecha_solicitud);
      this.titulo_proyecto = titulo_proyecto;
      this.telefono_contacto = telefono_contacto;
      this.codigo_proyecto = codigo_proyecto;
      this.observaciones_validacion = observaciones_validacion;
      this.observaciones_aprobacion = observaciones_aprobacion;
      this.fecha_validacion = corregirFecha(fecha_validacion);
      this.respuesta = respuesta;
      this.fecha_aprobacion = corregirFecha(fecha_aprobacion);
      this.fecha_actualizacion = corregirFecha(fecha_actualizacion);
      this.observaciones_actualizacion = observaciones_actualizacion;
      this.estado_tramite = estado_tramite;
      this.tipo_tramite = tipo_tramite;
      this.lista_miembros = lista_miembros;
      this.id_historial = id_historial;
      this.id_informe_avance = id_informe_avance;
      this.id_informe_final = id_informe_final;
      this.id_prorroga = id_prorroga;
      this.id_presupuesto = id_presupuesto;
      this.id_miembro = id_miembro;
   }

   public java.util.List<ucuenca.tramitesdiuc.documento> getDocumentos_adjuntos()
   {
      return this.documentos_adjuntos;
   }

   public void setDocumentos_adjuntos(
         java.util.List<ucuenca.tramitesdiuc.documento> documentos_adjuntos)
   {
      this.documentos_adjuntos = documentos_adjuntos;
   }

   public java.util.List<java.lang.String> getAaa()
   {
      return this.aaa;
   }

   public void setAaa(java.util.List<java.lang.String> aaa)
   {
      this.aaa = aaa;
   }
   
   public java.util.List<org.jbpm.document.Document> getAa()
   {
      return this.aa;
   }

   public void setAa(java.util.List<org.jbpm.document.Document> aa)
   {
      this.aa = aa;
   }

   public tramite(java.lang.Long id, java.text.SimpleDateFormat formatoFecha,
         java.lang.String solicitante, java.lang.String convocatoria,
         java.lang.Integer nro_tramite, java.util.Date fecha_solicitud,
         java.lang.String titulo_proyecto, java.lang.String telefono_contacto,
         java.lang.String codigo_proyecto,
         java.lang.String observaciones_validacion,
         java.lang.String observaciones_aprobacion,
         java.util.Date fecha_validacion, java.lang.String respuesta,
         java.util.Date fecha_aprobacion, java.util.Date fecha_actualizacion,
         java.lang.String observaciones_actualizacion,
         java.lang.String estado_tramite, java.lang.String tipo_tramite,
         java.util.List<ucuenca.tramitesdiuc.miembro> lista_miembros,
         java.lang.Long id_historial, java.lang.Long id_informe_avance,
         java.lang.Long id_informe_final, java.lang.Long id_prorroga,
         java.lang.Long id_presupuesto, java.lang.Long id_miembro,
         java.util.List<ucuenca.tramitesdiuc.documento> documentos_adjuntos,
         java.util.List<java.lang.String> aaa,
         java.util.List<org.jbpm.document.Document> aa)
   {
      this.id = id;
      this.formatoFecha = formatoFecha;
      this.solicitante = solicitante;
      this.convocatoria = convocatoria;
      this.nro_tramite = nro_tramite;
      this.fecha_solicitud = fecha_solicitud;
      this.titulo_proyecto = titulo_proyecto;
      this.telefono_contacto = telefono_contacto;
      this.codigo_proyecto = codigo_proyecto;
      this.observaciones_validacion = observaciones_validacion;
      this.observaciones_aprobacion = observaciones_aprobacion;
      this.fecha_validacion = fecha_validacion;
      this.respuesta = respuesta;
      this.fecha_aprobacion = fecha_aprobacion;
      this.fecha_actualizacion = fecha_actualizacion;
      this.observaciones_actualizacion = observaciones_actualizacion;
      this.estado_tramite = estado_tramite;
      this.tipo_tramite = tipo_tramite;
      this.lista_miembros = lista_miembros;
      this.id_historial = id_historial;
      this.id_informe_avance = id_informe_avance;
      this.id_informe_final = id_informe_final;
      this.id_prorroga = id_prorroga;
      this.id_presupuesto = id_presupuesto;
      this.id_miembro = id_miembro;
      this.documentos_adjuntos = documentos_adjuntos;
      this.aaa = aaa;
      this.aa = aa;
   }

}